# Generated by Django 3.0.7 on 2020-06-23 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvoted_answers',
            field=models.ManyToManyField(related_name='downvoted_users', to='questions.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_questions',
            field=models.ManyToManyField(related_name='downvoted_users', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='accounts.Following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_answers',
            field=models.ManyToManyField(related_name='upvoted_users', to='questions.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_questions',
            field=models.ManyToManyField(related_name='upvoted_users', to='questions.Question'),
        ),
    ]
